# Generated by Django 4.1.1 on 2022-09-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Kullanıcı adı')),
                ('firstname', models.CharField(max_length=150, verbose_name='İsim')),
                ('lastname', models.CharField(max_length=150, verbose_name='Soy isim')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phonenum', models.CharField(max_length=50, verbose_name='telefon numarası')),
                ('range', models.IntegerField(blank=True, null=True, verbose_name='Mesafe')),
                ('flighttime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='uçuş süresi')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Puanı')),
            ],
        ),
    ]
